Files Used:
* altlex_dev.tsv - grad student annotated data
* altlex_gold.tsv - CrowdFlower annotated data

Formatting: All data is tab-separated.

Columns: prevWords, altlex, currWords, and label.<br>
prevWords - text before the altlex<br>
altlex - the altlex itself<br>
currWords - text after the altlex<br>
label - 0, 1, or 2 representing none, reason, or result, respectively<br>

1. REASON : Effect-Signal-Cause : He did this TO PROTECT that.
2. RESULT: Cause-Signal-Effect : That thing he did LED TO this.
  
Files Not Used:
* altlex_train_paraphrases.tsv - paraphrases derived from English and Simple Wikipedia, respectively
* altlex_train.tsv - distant labeled data with causal and non-causal connectives
* altlex_train_bootstrapped.tsv - distant labeled data after two rounds of bootstrapping

### One File

In [1]:
import pandas as pd
import numpy as np
import re
import os

In [8]:
data_dir = r"D:\59 Github Projects\0009 CausalAltLex\HideyMckeown\data"
all_files = ['altlex_dev.tsv', 'altlex_gold.tsv']

file = all_files[1]
print(os.path.splitext(file)[0])
fn = os.path.join(data_dir, file)
original_data = pd.read_csv(fn, sep='\t')
original_data

altlex_gold

,prevWords,altlex,currWords,label
0,A government affidavit in 2006 stated that the...,caused,"558,125 injuries , including 38,478 temporary ...",2
1,The Indian government and local activists argu...,caused,a backflow of water into a MIC tank triggering...,2
2,The UCIL factory was,built in,1969 to produce the pesticide Sevin ( UCC 's b...,0
3,"In a panic , he removed his mask , inhaling a ...",which resulted in,his death 72 hours later .,2
4,"In August 1982 , a chemical engineer came into...",resulting in,burns over 30 percent of his body .,2
...,...,...,...,...
606,Then he turned into Angelus and when he was fi...,changed,"back ( after months , by Willow ) , Buffy stab...",0
607,"In Asia , the United States",led,the occupation of Japan and administrated Japa...,2
608,"In April 1940 , Germany invaded Denmark and No...",to protect,"shipments of iron ore from Sweden , which the ...",1
609,Musical analysis of a composition aims at achi...,leading to,more meaningful hearing and a greater apprecia...,2
610,"On May 27 , two aftershocks , one 5.2 Mw in Qi...",led to,"the collapse of more than 420,000 homes and in...",2

In [10]:
corpus = 'altlex'
cols = ['corpus','doc_id','sent_id','eg_id','index','text','text_w_pairs','seq_label','pair_label','context','num_sents']

data = []
for i, row in original_data.iterrows():
    
    sentid = str(i) # Not relevant for this dataset
    num_eg_for_this_sentid = 0 # Not relevant for this dataset
    identifiers = [corpus,os.path.basename(fn),str(sentid),str(num_eg_for_this_sentid)]
    unique_index = '_'.join(identifiers)
    
    text = str(row['prevWords']).strip()+' '+str(row['altlex']).strip()+' '+str(row['currWords']).strip()
    label = int(row['label'])
    seq_label = pair_label = 1 if label!=0 else 0
    
    if label == 2: #CAUSE->EFFECT || ARG0->ARG1
        text_w_pairs = '<ARG0>'+str(row['prevWords']).strip()+'</ARG0> '+str(row['altlex']).strip()+' <ARG1>'+str(row['currWords']).strip()+'</ARG1>'
    else:
        text_w_pairs = '<ARG1>'+str(row['prevWords']).strip()+'</ARG1> '+str(row['altlex']).strip()+' <ARG0>'+str(row['currWords']).strip()+'</ARG0>'
        
    data.append(
        identifiers+[
            unique_index,
            text.strip(),
            text_w_pairs.strip(),
            seq_label,
            pair_label,
            '',1
        ]
    )
    
data = pd.DataFrame(data, columns=cols)
data

,corpus,doc_id,sent_id,eg_id,index,text,text_w_pairs,seq_label,pair_label,context,num_sents
0,altlex,altlex_gold.tsv,0,0,altlex_altlex_gold.tsv_0_0,A government affidavit in 2006 stated that the...,<ARG0>A government affidavit in 2006 stated th...,1,1,,1
1,altlex,altlex_gold.tsv,1,0,altlex_altlex_gold.tsv_1_0,The Indian government and local activists argu...,<ARG0>The Indian government and local activist...,1,1,,1
2,altlex,altlex_gold.tsv,2,0,altlex_altlex_gold.tsv_2_0,The UCIL factory was built in 1969 to produce ...,<ARG1>The UCIL factory was</ARG1> built in <AR...,0,0,,1
3,altlex,altlex_gold.tsv,3,0,altlex_altlex_gold.tsv_3_0,"In a panic , he removed his mask , inhaling a ...","<ARG0>In a panic , he removed his mask , inhal...",1,1,,1
4,altlex,altlex_gold.tsv,4,0,altlex_altlex_gold.tsv_4_0,"In August 1982 , a chemical engineer came into...","<ARG0>In August 1982 , a chemical engineer cam...",1,1,,1
...,...,...,...,...,...,...,...,...,...,...,...
606,altlex,altlex_gold.tsv,606,0,altlex_altlex_gold.tsv_606_0,Then he turned into Angelus and when he was fi...,<ARG1>Then he turned into Angelus and when he ...,0,0,,1
607,altlex,altlex_gold.tsv,607,0,altlex_altlex_gold.tsv_607_0,"In Asia , the United States led the occupation...","<ARG0>In Asia , the United States</ARG0> led <...",1,1,,1
608,altlex,altlex_gold.tsv,608,0,altlex_altlex_gold.tsv_608_0,"In April 1940 , Germany invaded Denmark and No...","<ARG1>In April 1940 , Germany invaded Denmark ...",1,1,,1
609,altlex,altlex_gold.tsv,609,0,altlex_altlex_gold.tsv_609_0,Musical analysis of a composition aims at achi...,<ARG0>Musical analysis of a composition aims a...,1,1,,1
610,altlex,altlex_gold.tsv,610,0,altlex_altlex_gold.tsv_610_0,"On May 27 , two aftershocks , one 5.2 Mw in Qi...","<ARG0>On May 27 , two aftershocks , one 5.2 Mw...",1,1,,1

In [23]:
# Number of duplicated rows
sum(data.duplicated(subset=['text']))

34

In [25]:
data[data.duplicated(subset=['text'], keep=False)].sort_values(by=['text'])

,corpus,doc_id,sent_id,eg_id,index,text,text_w_pairs,seq_label,pair_label,context,num_sents
89,altlex,altlex_gold.tsv,89,0,altlex_altlex_gold.tsv_89_0,Although first feared that Nalgae would cause ...,<ARG0>Although first feared that Nalgae would<...,1,1,,1
90,altlex,altlex_gold.tsv,90,0,altlex_altlex_gold.tsv_90_0,Although first feared that Nalgae would cause ...,<ARG0>Although first feared that Nalgae would ...,1,1,,1
128,altlex,altlex_gold.tsv,128,0,altlex_altlex_gold.tsv_128_0,DR6 is highly expressed in the human brain reg...,<ARG0>DR6 is highly expressed in the human bra...,1,1,,1
127,altlex,altlex_gold.tsv,127,0,altlex_altlex_gold.tsv_127_0,DR6 is highly expressed in the human brain reg...,<ARG0>DR6 is highly expressed in the human bra...,1,1,,1
212,altlex,altlex_gold.tsv,212,0,altlex_altlex_gold.tsv_212_0,Each circuit represents a bit ( binary digit )...,<ARG0>Each circuit represents a bit ( binary d...,1,1,,1
...,...,...,...,...,...,...,...,...,...,...,...
34,altlex,altlex_gold.tsv,34,0,altlex_altlex_gold.tsv_34_0,The seismicity of central and eastern Asia is ...,<ARG1>The seismicity of central and eastern As...,1,1,,1
172,altlex,altlex_gold.tsv,172,0,altlex_altlex_gold.tsv_172_0,Then he turned into Angelus and when he was fi...,<ARG1>Then he turned into Angelus and when he ...,1,1,,1
606,altlex,altlex_gold.tsv,606,0,altlex_altlex_gold.tsv_606_0,Then he turned into Angelus and when he was fi...,<ARG1>Then he turned into Angelus and when he ...,0,0,,1
151,altlex,altlex_gold.tsv,151,0,altlex_altlex_gold.tsv_151_0,Vampires Spike and Drusilla ( weakened from a ...,<ARG1>Vampires Spike and Drusilla ( weakened f...,1,1,,1
152,altlex,altlex_gold.tsv,152,0,altlex_altlex_gold.tsv_152_0,Vampires Spike and Drusilla ( weakened from a ...,<ARG1>Vampires Spike and Drusilla ( weakened f...,1,1,,1

In [45]:
grouped = data[data.duplicated(subset=['text'], keep=False)][['text','seq_label']].groupby(['text']).mean().reset_index()

for _, row in grouped[(grouped['seq_label']>0) & (grouped['seq_label']<1)].iterrows():
    # Replace values of dataframe inplace
    data.at[data[data['text']==row['text']].index, 'seq_label'] = 1
data

,corpus,doc_id,sent_id,eg_id,index,text,text_w_pairs,seq_label,pair_label,context,num_sents
0,altlex,altlex_gold.tsv,0,0,altlex_altlex_gold.tsv_0_0,A government affidavit in 2006 stated that the...,<ARG0>A government affidavit in 2006 stated th...,1,1,,1
1,altlex,altlex_gold.tsv,1,0,altlex_altlex_gold.tsv_1_0,The Indian government and local activists argu...,<ARG0>The Indian government and local activist...,1,1,,1
2,altlex,altlex_gold.tsv,2,0,altlex_altlex_gold.tsv_2_0,The UCIL factory was built in 1969 to produce ...,<ARG1>The UCIL factory was</ARG1> built in <AR...,0,0,,1
3,altlex,altlex_gold.tsv,3,0,altlex_altlex_gold.tsv_3_0,"In a panic , he removed his mask , inhaling a ...","<ARG0>In a panic , he removed his mask , inhal...",1,1,,1
4,altlex,altlex_gold.tsv,4,0,altlex_altlex_gold.tsv_4_0,"In August 1982 , a chemical engineer came into...","<ARG0>In August 1982 , a chemical engineer cam...",1,1,,1
...,...,...,...,...,...,...,...,...,...,...,...
606,altlex,altlex_gold.tsv,606,0,altlex_altlex_gold.tsv_606_0,Then he turned into Angelus and when he was fi...,<ARG1>Then he turned into Angelus and when he ...,1,0,,1
607,altlex,altlex_gold.tsv,607,0,altlex_altlex_gold.tsv_607_0,"In Asia , the United States led the occupation...","<ARG0>In Asia , the United States</ARG0> led <...",1,1,,1
608,altlex,altlex_gold.tsv,608,0,altlex_altlex_gold.tsv_608_0,"In April 1940 , Germany invaded Denmark and No...","<ARG1>In April 1940 , Germany invaded Denmark ...",1,1,,1
609,altlex,altlex_gold.tsv,609,0,altlex_altlex_gold.tsv_609_0,Musical analysis of a composition aims at achi...,<ARG0>Musical analysis of a composition aims a...,1,1,,1
610,altlex,altlex_gold.tsv,610,0,altlex_altlex_gold.tsv_610_0,"On May 27 , two aftershocks , one 5.2 Mw in Qi...","<ARG0>On May 27 , two aftershocks , one 5.2 Mw...",1,1,,1

In [46]:
# There should be some rows
data.loc[(data['seq_label'])==1 & (data['pair_label']==0)]

,corpus,doc_id,sent_id,eg_id,index,text,text_w_pairs,seq_label,pair_label,context,num_sents
77,altlex,altlex_gold.tsv,77,0,altlex_altlex_gold.tsv_77_0,"Over the next two days , the system drifted no...","<ARG1>Over the next two days , the system drif...",1,0,,1
142,altlex,altlex_gold.tsv,142,0,altlex_altlex_gold.tsv_142_0,The clinical symptoms of AD usually occurs aft...,<ARG1>The clinical symptoms of AD usually occu...,1,0,,1
204,altlex,altlex_gold.tsv,204,0,altlex_altlex_gold.tsv_204_0,"Furthermore , jump instructions may be made to...","<ARG1>Furthermore , jump instructions may be m...",1,0,,1
213,altlex,altlex_gold.tsv,213,0,altlex_altlex_gold.tsv_213_0,Each circuit represents a bit ( binary digit )...,<ARG1>Each circuit represents a bit ( binary d...,1,0,,1
224,altlex,altlex_gold.tsv,224,0,altlex_altlex_gold.tsv_224_0,Many projects try to send working computers to...,<ARG1>Many projects try to send working comput...,1,0,,1
231,altlex,altlex_gold.tsv,231,0,altlex_altlex_gold.tsv_231_0,"On October 25 at 1:45 am EDT , Kennedy respond...","<ARG1>On October 25 at 1:45 am EDT , Kennedy r...",1,0,,1
354,altlex,altlex_gold.tsv,354,0,altlex_altlex_gold.tsv_354_0,Many commanders on both sides knew that such w...,<ARG1>Many commanders on both sides knew that ...,1,0,,1
366,altlex,altlex_gold.tsv,366,0,altlex_altlex_gold.tsv_366_0,The UK government placed Ireland under martial...,<ARG1>The UK government placed Ireland under m...,1,0,,1
480,altlex,altlex_gold.tsv,480,0,altlex_altlex_gold.tsv_480_0,The large number of head wounds caused by expl...,<ARG1>The large number of head wounds caused b...,1,0,,1
484,altlex,altlex_gold.tsv,484,0,altlex_altlex_gold.tsv_484_0,"On May 27 , two aftershocks , one 5.2 Mw in Qi...","<ARG1>On May 27 , two aftershocks , one 5.2 Mw...",1,0,,1
606,altlex,altlex_gold.tsv,606,0,altlex_altlex_gold.tsv_606_0,Then he turned into Angelus and when he was fi...,<ARG1>Then he turned into Angelus and when he ...,1,0,,1

### Mass Run

In [40]:
import pandas as pd
import numpy as np
from collections import defaultdict
import re
import os

data_dir = r"D:\59 Github Projects\0009 CausalAltLex\HideyMckeown\data"
all_filenames = ['altlex_dev.tsv', 'altlex_gold.tsv']
cols = ['corpus','doc_id','sent_id','eg_id','index','text','text_w_pairs','seq_label','pair_label','context','num_sents']


def run(file):
    # Open File
    fn = os.path.join(data_dir, file)
    original_data = pd.read_csv(fn, sep='\t')
    original_data = original_data.dropna(subset=['prevWords','currWords'])
    original_data['text'] = [
        str(p).strip()+' '+str(a).strip()+' '+str(c).strip() \
        for p,a,c in zip(original_data['prevWords'], original_data['altlex'], original_data['currWords'])
    ]
    
    # Add SentId
    original_data['sentid'] = original_data[['text']].sum(axis=1).map(hash)
    hashmap = {s:i for i,s in enumerate(original_data['sentid'].unique())}
    original_data['sentid'] = original_data['sentid'].apply(lambda x: hashmap[x])
    
    # Format
    data = []
    corpus = 'altlex'
    sentid_counter = defaultdict(int)
    for i, row in original_data.iterrows():

        sentid = str(row['sentid']) # Always single sentences for AltLex corpus
        num_eg_for_this_sentid = sentid_counter[sentid]
        identifiers = [corpus,os.path.basename(fn),str(sentid),str(num_eg_for_this_sentid)]
        unique_index = '_'.join(identifiers)

        text = row['text']
        label = int(row['label'])
        seq_label = pair_label = 1 if label!=0 else 0
            
        if label == 2: #CAUSE->EFFECT || ARG0->ARG1
            text_w_pairs = '<ARG0>'+str(row['prevWords']).strip()+'</ARG0> '+str(row['altlex']).strip()+' <ARG1>'+str(row['currWords']).strip()+'</ARG1>'
        else:
            text_w_pairs = '<ARG1>'+str(row['prevWords']).strip()+'</ARG1> '+str(row['altlex']).strip()+' <ARG0>'+str(row['currWords']).strip()+'</ARG0>'

        data.append(
            identifiers+[
                unique_index,
                text.strip(),
                text_w_pairs.strip(),
                seq_label,
                pair_label,
                '',1
            ]
        )
        sentid_counter[sentid]+=1

    data = pd.DataFrame(data, columns=cols)
    data['sent_id'] = data['sent_id'].astype(str)
    data['seq_label'] = data.groupby(['corpus','doc_id','sent_id'])['seq_label'].transform('max')
    
    return data

run(all_filenames[0])

,corpus,doc_id,sent_id,eg_id,index,text,text_w_pairs,seq_label,pair_label,context,num_sents
0,altlex,altlex_dev.tsv,0,0,altlex_altlex_dev.tsv_0_0,"The Bhopal disaster , also referred to as the ...","<ARG1>The Bhopal disaster , also referred to</...",0,0,,1
1,altlex,altlex_dev.tsv,1,0,altlex_altlex_dev.tsv_1_0,"In addition , several vent gas scrubbers had b...","<ARG1>In addition , several vent gas scrubbers...",0,0,,1
2,altlex,altlex_dev.tsv,2,0,altlex_altlex_dev.tsv_2_0,Union Carbide organized a team of internationa...,<ARG1>Union Carbide organized a team of intern...,0,0,,1
3,altlex,altlex_dev.tsv,3,0,altlex_altlex_dev.tsv_3_0,"Following an appeal of this decision , the U.S...","<ARG1>Following an appeal of this decision , t...",0,0,,1
4,altlex,altlex_dev.tsv,4,0,altlex_altlex_dev.tsv_4_0,The U.S. Supreme Court refused to hear an appe...,<ARG0>The U.S. Supreme Court refused to hear a...,1,1,,1
...,...,...,...,...,...,...,...,...,...,...,...
411,altlex,altlex_dev.tsv,396,0,altlex_altlex_dev.tsv_396_0,Bad economies and people wanting to rule thems...,<ARG1>Bad economies and people wanting to rule...,1,1,,1
412,altlex,altlex_dev.tsv,397,0,altlex_altlex_dev.tsv_397_0,The United States became richer than any other...,<ARG1>The United States became richer than any...,0,0,,1
413,altlex,altlex_dev.tsv,398,0,altlex_altlex_dev.tsv_398_0,"Between 1942 and 1945 , Roosevelt signed an or...","<ARG1>Between 1942</ARG1> and <ARG0>1945 , Roo...",0,0,,1
414,altlex,altlex_dev.tsv,399,0,altlex_altlex_dev.tsv_399_0,"The Resistance , the group of people who fough...","<ARG1>The Resistance , the group of people who...",0,0,,1
415,altlex,altlex_dev.tsv,400,0,altlex_altlex_dev.tsv_400_0,Portable machine guns became widely used .,<ARG1>Portable machine guns became widely</ARG...,0,0,,1

In [41]:
data = pd.DataFrame()
for counter, file in enumerate(all_filenames):

    df = run(file)
    data = pd.concat([data, df])

data

,corpus,doc_id,sent_id,eg_id,index,text,text_w_pairs,seq_label,pair_label,context,num_sents
0,altlex,altlex_dev.tsv,0,0,altlex_altlex_dev.tsv_0_0,"The Bhopal disaster , also referred to as the ...","<ARG1>The Bhopal disaster , also referred to</...",0,0,,1
1,altlex,altlex_dev.tsv,1,0,altlex_altlex_dev.tsv_1_0,"In addition , several vent gas scrubbers had b...","<ARG1>In addition , several vent gas scrubbers...",0,0,,1
2,altlex,altlex_dev.tsv,2,0,altlex_altlex_dev.tsv_2_0,Union Carbide organized a team of internationa...,<ARG1>Union Carbide organized a team of intern...,0,0,,1
3,altlex,altlex_dev.tsv,3,0,altlex_altlex_dev.tsv_3_0,"Following an appeal of this decision , the U.S...","<ARG1>Following an appeal of this decision , t...",0,0,,1
4,altlex,altlex_dev.tsv,4,0,altlex_altlex_dev.tsv_4_0,The U.S. Supreme Court refused to hear an appe...,<ARG0>The U.S. Supreme Court refused to hear a...,1,1,,1
...,...,...,...,...,...,...,...,...,...,...,...
606,altlex,altlex_gold.tsv,162,1,altlex_altlex_gold.tsv_162_1,Then he turned into Angelus and when he was fi...,<ARG1>Then he turned into Angelus and when he ...,1,0,,1
607,altlex,altlex_gold.tsv,574,0,altlex_altlex_gold.tsv_574_0,"In Asia , the United States led the occupation...","<ARG0>In Asia , the United States</ARG0> led <...",1,1,,1
608,altlex,altlex_gold.tsv,575,0,altlex_altlex_gold.tsv_575_0,"In April 1940 , Germany invaded Denmark and No...","<ARG1>In April 1940 , Germany invaded Denmark ...",1,1,,1
609,altlex,altlex_gold.tsv,576,0,altlex_altlex_gold.tsv_576_0,Musical analysis of a composition aims at achi...,<ARG0>Musical analysis of a composition aims a...,1,1,,1
610,altlex,altlex_gold.tsv,459,1,altlex_altlex_gold.tsv_459_1,"On May 27 , two aftershocks , one 5.2 Mw in Qi...","<ARG0>On May 27 , two aftershocks , one 5.2 Mw...",1,1,,1

In [42]:
# There should be some rows
data.loc[(data['seq_label'])==1 & (data['pair_label']==0)]

,corpus,doc_id,sent_id,eg_id,index,text,text_w_pairs,seq_label,pair_label,context,num_sents
192,altlex,altlex_dev.tsv,181,1,altlex_altlex_dev.tsv_181_1,The resulting lack of coverage over the island...,<ARG1>The resulting lack of coverage over the ...,1,0,,1
228,altlex,altlex_dev.tsv,217,0,altlex_altlex_dev.tsv_217_0,"Camulodunum was burned to the ground , as well...","<ARG1>Camulodunum was burned to the ground , a...",1,0,,1
308,altlex,altlex_dev.tsv,294,1,altlex_altlex_dev.tsv_294_1,"But despite its unsuitability , and the availa...","<ARG1>But despite its unsuitability , and the ...",1,0,,1
77,altlex,altlex_gold.tsv,75,0,altlex_altlex_gold.tsv_75_0,"Over the next two days , the system drifted no...","<ARG1>Over the next two days , the system drif...",1,0,,1
142,altlex,altlex_gold.tsv,133,1,altlex_altlex_gold.tsv_133_1,The clinical symptoms of AD usually occurs aft...,<ARG1>The clinical symptoms of AD usually occu...,1,0,,1
204,altlex,altlex_gold.tsv,191,1,altlex_altlex_gold.tsv_191_1,"Furthermore , jump instructions may be made to...","<ARG1>Furthermore , jump instructions may be m...",1,0,,1
213,altlex,altlex_gold.tsv,199,1,altlex_altlex_gold.tsv_199_1,Each circuit represents a bit ( binary digit )...,<ARG1>Each circuit represents a bit ( binary d...,1,0,,1
224,altlex,altlex_gold.tsv,209,1,altlex_altlex_gold.tsv_209_1,Many projects try to send working computers to...,<ARG1>Many projects try to send working comput...,1,0,,1
231,altlex,altlex_gold.tsv,215,0,altlex_altlex_gold.tsv_215_0,"On October 25 at 1:45 am EDT , Kennedy respond...","<ARG1>On October 25 at 1:45 am EDT , Kennedy r...",1,0,,1
354,altlex,altlex_gold.tsv,334,0,altlex_altlex_gold.tsv_334_0,Many commanders on both sides knew that such w...,<ARG1>Many commanders on both sides knew that ...,1,0,,1
366,altlex,altlex_gold.tsv,344,1,altlex_altlex_gold.tsv_344_1,The UK government placed Ireland under martial...,<ARG1>The UK government placed Ireland under m...,1,0,,1
480,altlex,altlex_gold.tsv,326,2,altlex_altlex_gold.tsv_326_2,The large number of head wounds caused by expl...,<ARG1>The large number of head wounds caused b...,1,0,,1
484,altlex,altlex_gold.tsv,459,0,altlex_altlex_gold.tsv_459_0,"On May 27 , two aftershocks , one 5.2 Mw in Qi...","<ARG1>On May 27 , two aftershocks , one 5.2 Mw...",1,0,,1
606,altlex,altlex_gold.tsv,162,1,altlex_altlex_gold.tsv_162_1,Then he turned into Angelus and when he was fi...,<ARG1>Then he turned into Angelus and when he ...,1,0,,1

In [43]:
from collections import Counter

print('All Examples')
print('Seq Level:', Counter(data['seq_label'])) # if sentence level causality exists
print('Pair Level:',Counter(data['pair_label'])) # if ARG0-ARG1 pair level causality exists
print('Seq Level (Unique):',Counter(data.drop_duplicates(subset=['corpus','doc_id','sent_id'])['seq_label']))

print('\nSingle Sentence Examples')
print('Seq Level:', Counter(data.loc[data['num_sents']==1,'seq_label'])) # if sentence level causality exists
print('Pair Level:', Counter(data.loc[data['num_sents']==1,'pair_label'])) # if ARG0-ARG1 pair level causality exists
print('Seq Level (Unique):',Counter(data.loc[data['num_sents']==1].drop_duplicates(subset=['corpus','doc_id','sent_id'])['seq_label']))

All Examples
Seq Level: Counter({0: 571, 1: 456})
Pair Level: Counter({0: 585, 1: 442})
Seq Level (Unique): Counter({0: 563, 1: 415})

Single Sentence Examples
Seq Level: Counter({0: 571, 1: 456})
Pair Level: Counter({0: 585, 1: 442})
Seq Level (Unique): Counter({0: 563, 1: 415})

In [44]:
data.to_csv('cleaned/altlex.csv', index=False,encoding='utf-8-sig')

In [ ]:
# import pandas as pd
# import numpy as np
# import re
# import os

# data_dir = r"D:\59 Github Projects\0009 CausalAltLex\HideyMckeown\data"
# all_filenames = ['altlex_dev.tsv', 'altlex_gold.tsv']
# corpus = 'altlex'
# cols = ['corpus','doc_id','sent_id','eg_id','index','text','text_w_pairs','seq_label','pair_label','context','num_sents']


# def run(file):
#     # Open File
#     fn = os.path.join(data_dir, file)
#     original_data = pd.read_csv(fn, sep='\t')
#     original_data = original_data.dropna(subset=['prevWords','currWords'])
    
#     # Format
#     data = []
#     for i, row in original_data.iterrows():

#         sentid = str(i) # Not relevant for this dataset
#         num_eg_for_this_sentid = 0 # Not relevant for this dataset
#         identifiers = [corpus,os.path.basename(fn),str(sentid),str(num_eg_for_this_sentid)]
#         unique_index = '_'.join(identifiers)

#         text = str(row['prevWords']).strip()+' '+str(row['altlex']).strip()+' '+str(row['currWords']).strip()
#         label = int(row['label'])
#         seq_label = pair_label = 1 if label!=0 else 0

#         if label == 2: #CAUSE->EFFECT || ARG0->ARG1
#             text_w_pairs = '<ARG0>'+str(row['prevWords']).strip()+'</ARG0> '+str(row['altlex']).strip()+' <ARG1>'+str(row['currWords']).strip()+'</ARG1>'
#         else:
#             text_w_pairs = '<ARG1>'+str(row['prevWords']).strip()+'</ARG1> '+str(row['altlex']).strip()+' <ARG0>'+str(row['currWords']).strip()+'</ARG0>'

#         data.append(
#             identifiers+[
#                 unique_index,
#                 text.strip(),
#                 text_w_pairs.strip(),
#                 seq_label,
#                 pair_label,
#                 '',1
#             ]
#         )
    
#     data = pd.DataFrame(data, columns=cols)
    
#     # Clean
#     grouped = data[data.duplicated(subset=['text'], keep=False)][['text','seq_label']].groupby(['text']).mean().reset_index()
#     for _, row in grouped[(grouped['seq_label']>0) & (grouped['seq_label']<1)].iterrows():
#         # Replace values of dataframe inplace
#         data.at[data[data['text']==row['text']].index, 'seq_label'] = 1
        
#     return data

# run(all_files[0])