In [1]:
import pandas as pd
import numpy as np


def run(st1,st2):
    cols = ['corpus','doc_id','sent_id','eg_id','index','text','text_w_pairs','seq_label','pair_label','context','num_sents']

    # merge
    data = st1[['index','text','label']].merge(
        st2[['doc_id','eg_id','text','text_w_pairs']], 
        how='outer', left_on='index', right_on='doc_id'
    )
    data['corpus']='cnc'
    data['text'] = data['text_y'].fillna(data['text_x'])
    data = data.drop(columns=['doc_id','text_x','text_y'])
    data = data.rename(columns={'index':'doc_id','label':'pair_label'})
    data['seq_label'] = data['pair_label']
    data['sent_id'] = 0 # all individual sentences
    data['context'] = ''
    data['num_sents'] = 1
    data['eg_id'] = data['eg_id'].fillna(0)
    data['eg_id'] = data['eg_id']
    data['seq_label'] = data.groupby(['corpus','doc_id','sent_id'])['seq_label'].transform('max')
    data['text_w_pairs'] = data['text_w_pairs'].fillna('')
    data['index'] = data['corpus']+'_'+data['doc_id'].astype(str)+'_'+data['sent_id'].astype(str)+'_'+data['eg_id'].astype(int).astype(str)
    data = data[cols]
    return data

In [2]:
st1_file = r"D:\61 Challenges\2022_CASE_\CodaLab\03. Official Datasets\Subtask 1\all_train_subtask1.csv"
st2_file = r"D:\61 Challenges\2022_CASE_\WebAnno\reviewing_annotations\Subtask2\07. Round5\curation\reviewed_all_train.csv"

st1 = pd.read_csv(st1_file)
st2 = pd.read_csv(st2_file)
train_df = run(st1,st2)
train_df

,corpus,doc_id,sent_id,eg_id,index,text,text_w_pairs,seq_label,pair_label,context,num_sents
0,cnc,train_01_0,0,0.0,cnc_train_01_0_0_0,The State alleged they hacked Sabata Petros Ch...,,1,1,,1
1,cnc,train_01_1,0,0.0,cnc_train_01_1_0_0,Chale was allegedly chased by a group of about...,,0,0,,1
2,cnc,train_01_2,0,0.0,cnc_train_01_2_0_0,His attackers allegedly drank his blood .,,0,0,,1
3,cnc,train_01_3,0,0.0,cnc_train_01_3_0_0,Tip asked Mathunjwa why he had not `` explicit...,,0,0,,1
4,cnc,train_01_4,0,0.0,cnc_train_01_4_0_0,`` It the protest was something which happened...,,0,0,,1
...,...,...,...,...,...,...,...,...,...,...,...
3269,cnc,train_10_318,0,0.0,cnc_train_10_318_0_0,"Police spokesman , Lieutenant Colonel Thulani ...",,0,0,,1
3270,cnc,train_10_319,0,0.0,cnc_train_10_319_0_0,"National Freedom Party spokesman , Sabelo Sigu...",,1,1,,1
3271,cnc,train_10_320,0,0.0,cnc_train_10_320_0_0,He described the shooting as `` evil '' .,,0,0,,1
3272,cnc,train_10_321,0,0.0,cnc_train_10_321_0_0,"On Sunday , three explosions in the south of t...",,1,1,,1
3273,cnc,train_10_322,0,0.0,cnc_train_10_322_0_0,Uighur groups abroad say the clashes are a des...,,1,1,,1

In [3]:
st1_file = r"D:\61 Challenges\2022_CASE_\CodaLab\03. Official Datasets\Subtask 1\test_subtask1.csv"
st2_file = r"D:\61 Challenges\2022_CASE_\WebAnno\reviewing_annotations\Subtask2\07. Round5\curation\reviewed_all_test.csv"

st1 = pd.read_csv(st1_file)
st2 = pd.read_csv(st2_file)
test_df = run(st1,st2)

In [4]:
data = pd.concat([train_df, test_df], axis=0)
data.head()

,corpus,doc_id,sent_id,eg_id,index,text,text_w_pairs,seq_label,pair_label,context,num_sents
0,cnc,train_01_0,0,0.0,cnc_train_01_0_0_0,The State alleged they hacked Sabata Petros Ch...,,1,1,,1
1,cnc,train_01_1,0,0.0,cnc_train_01_1_0_0,Chale was allegedly chased by a group of about...,,0,0,,1
2,cnc,train_01_2,0,0.0,cnc_train_01_2_0_0,His attackers allegedly drank his blood .,,0,0,,1
3,cnc,train_01_3,0,0.0,cnc_train_01_3_0_0,Tip asked Mathunjwa why he had not `` explicit...,,0,0,,1
4,cnc,train_01_4,0,0.0,cnc_train_01_4_0_0,`` It the protest was something which happened...,,0,0,,1

In [5]:
data.dropna().to_csv('cleaned/cnc.csv', index=False,encoding='utf-8-sig')